-- CREATE
CREATE TABLE BOOK(
    NO          NUMBER,
    TITLE       VARCHAR2(30),
    WRITER      VARCHAR2(30),
    PUBLISHER   VARCHAR2(30)
);

-- SELECT
SELECT * FROM BOOK;

-- INSERT
INSERT INTO BOOK(NO, TITLE, WRITER, PUBLISHER)
VALUES(1, 'NAME01', 'WRITER01', 'PUBLISHER01');
INSERT INTO BOOK(NO, TITLE, WRITER, PUBLISHER)
VALUES(2, 'NAME02', 'WRITER02', 'PUBLISHER02');

-- UPDATE
UPDATE BOOK SET TITLE = 'NAME01_UPDATE' WHERE NO = 1;

-- DELETE
DELETE FROM BOOK WHERE NO = 2;

-- DROP
DROP TABLE BOOK;