DROP SEQUENCE SEQ_SING;
CREATE SEQUENCE SEQ_SING NOCACHE NOCYCLE;

DROP TABLE SING CASCADE CONSTRAINTS;
CREATE TABLE SING(
  NO NUMBER PRIMARY KEY
  ,TITLE VARCHAR2(100) NOT NULL
  ,RELEASE_DATE TIMESTAMP DEFAULT SYSDATE
  ,SINGER VARCHAR2(100) NOT NULL
  ,COMPOSER VARCHAR2(100) NOT NULL
  ,DEL_YN CHAR(1)  DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);


INSERT INTO SING(
    NO,
    TITLE,
    RELEASE_DATE,
    SINGER,
    COMPOSER
)VALUES(
    SEQ_SING.NEXTVAL,
    '±Ë¡§øÌ¿Ã√„√·¥Ÿ',
    '2025-11-11',
    '±Ë¡§øÌ',
    '±Ë¡§øÌ22'
);

SELECT * FROM SING;