-- TABLE
DROP TABLE PLAYER CASCADE CONSTRAINTS;
CREATE TABLE PLAYER(
    NO                  NUMBER          PRIMARY KEY
    , POSITION          VARCHAR2(100)   NOT NULL
    , NAME              VARCHAR2(100)   NOT NULL
    , AGE               VARCHAR2(100)   NOT NULL
    , ENROLL_DATE       DATE            DEFAULT TRUNC(SYSDATE)
    , CONTRACT_PERIOD   DATE            DEFAULT TRUNC(SYSDATE)
    , WEEKLY_SALARY     NUMBER          NOT NULL
);

-- SEQUENCE
DROP SEQUENCE SEQ_PLAYER;
CREATE SEQUENCE SEQ_PLAYER NOCYCLE NOCACHE;

-- INSERT
INSERT INTO PLAYER(NO, POSITION , NAME, AGE, CONTRACT_PERIOD, WEEKLY_SALARY ) 
VALUES (SEQ_PLAYER.NEXTVAL, ?, ?, ?, ADD_MONTHS(SYSDATE, ?), ?);

INSERT INTO PLAYER(NO, POSITION , NAME, AGE, CONTRACT_PERIOD, WEEKLY_SALARY ) 
VALUES (SEQ_PLAYER.NEXTVAL, 'FW', '손흥민', '30', ADD_MONTHS(SYSDATE, 24), 100000000);

-- DELETE
DELETE PLAYER
WHERE NO = ?
;

-- UPDATE
UPDATE PLAYER
    SET
        POSITION = ?
        , AGE = ?
WHERE NO = ?
;

-- RESIGN
UPDATE PLAYER
    SET
        CONTRACT_PERIOD = ADD_MONTHS(SYSDATE, ?)
        , WEEKLY_SALARY = ?
WHERE NO = ?
;

-- SELECT (목록조회)
SELECT 	
    NO
    , POSITION
    , NAME
    , AGE
FROM PLAYER
ORDER BY POSITION ASC
;

-- SELECT (상세조회)
SELECT * FROM PLAYER
WHERE NO = &NO
;

-- SELECT SALARY SUM (주급지출 합 조회)
SELECT SUM(WEEKLY_SALARY) AS "선수단 주급 총합"
FROM PLAYER
WHERE CONTRACT_PERIOD > SYSDATE
;