---------------------------------------------------
---------------------- 삭제 ------------------------
---------------------------------------------------
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_ADMIN;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD_ATTACHMENT;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_REPLY;
DROP SEQUENCE SEQ_CATEGORY;
DROP SEQUENCE SEQ_NOTICE_REPLY;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE BOARD_REPLY CASCADE CONSTRAINTS;
DROP TABLE NOTICE_REPLY CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_ITEM_11 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ITEM_12 NOCACHE NOCYCLE;


CREATE SEQUENCE SEQ_ITEM_13 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ITEM_14 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ITEM_15 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ITEM_16 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ITEM_17 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ITEM_18 NOCACHE NOCYCLE;

SELECT SEQ_PRODUCT_INQUIRY.NEXTVAL AS NEXT_VALUE FROM DUAL;

SELECT SEQ_PRODUCT_INQUIRY.CURRVAL FROM DUAL;

---------------------------------------------------
--------------------- 시퀀스 -----------------------
---------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER              NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_ATTACHMENT    NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE              NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPLY               NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORY            NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTICE_REPLY            NOCACHE NOCYCLE;
---------------------------------------------------
--------------------- 테이블 -----------------------
---------------------------------------------------
CREATE TABLE MEMBER(
    NO          NUMBER          PRIMARY KEY
    , ID        VARCHAR2(100)   NOT NULL UNIQUE
    , PWD       VARCHAR2(100)   NOT NULL
    , NICK      VARCHAR2(100)   NOT NULL UNIQUE
    , DEL_YN    CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
    , ENROLL_DATE TIMESTAMP     DEFAULT SYSDATE
    , MODIFY_DATE TIMESTAMP 
);

CREATE TABLE ADMIN(
    NO          NUMBER          PRIMARY KEY
    , ID        VARCHAR2(100)   NOT NULL UNIQUE
    , PWD       VARCHAR2(100)   NOT NULL
    , NICK      VARCHAR2(100)   NOT NULL UNIQUE
    , DEL_YN    CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , CATEGORY_NO   NUMBER          
    , WRITER_NO     NUMBER          NOT NULL
    , HIT           NUMBER          DEFAULT 0
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD_ATTACHMENT(
    NO              NUMBER          PRIMARY KEY
    , REF_NO        NUMBER          NOT NULL
    , ORIGIN_NAME   VARCHAR2(255)   
    , CHANGE_NAME   VARCHAR2(255)   NOT NULL UNIQUE
    , UPLOAD_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N'
);

CREATE TABLE NOTICE(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , HIT           NUMBER          DEFAULT 0
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD_REPLY(
    NO              NUMBER          PRIMARY KEY
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , REF_NO        NUMBER          NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);
CREATE TABLE NOTICE_REPLY(
    NO              NUMBER          PRIMARY KEY
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , REF_NO        NUMBER          NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , CREATE_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE CATEGORY(
    NO              NUMBER          PRIMARY KEY
    , NAME          VARCHAR2(30)    NOT NULL UNIQUE
);

SEQ_PRODUCT_INQUIRY.CURRVAL;

---------------------------------------------------
--------------------- 외래키 -----------------------
---------------------------------------------------
ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_BOARD FOREIGN KEY (WRITER_NO) REFERENCES ADMIN(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(NO);
ALTER TABLE BOARD_ATTACHMENT ADD CONSTRAINT FK_BOARD_ATTACHMENT_BOARD FOREIGN KEY (REF_NO) REFERENCES BOARD(NO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT FK_BOARD_REPLY_BOARD FOREIGN KEY (REF_NO) REFERENCES BOARD(NO);
ALTER TABLE BOARD_REPLY ADD CONSTRAINT FK_BOARD_REPLY_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE NOTICE_REPLY ADD CONSTRAINT FK_NOTICE_REPLY_BOARD FOREIGN KEY (REF_NO) REFERENCES NOTICE(NO);
ALTER TABLE NOTICE_REPLY ADD CONSTRAINT FK_NOTICE_REPLY_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

---------------------------------------------------
--------------------- 데이터 -----------------------
---------------------------------------------------
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'master' , '1234', '마스터');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin' , '1234', '운영자');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin01' , '1234', '운영자1');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin02' , '1234', '운영자2');
INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL, 'admin031' , '1234', '운영자3');
COMMIT;

INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '자유');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '운동');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '게임');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '개발');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '자바');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '코딩');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '낚시');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '요리');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '댄스');
INSERT INTO CATEGORY(NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '기타');
COMMIT;

---------------------------------------
---------BOARD
-----------------------------------
SELECT * FROM MEMBER;
SELECT * FROM BOARD;
-- 게시글 작성

INSERT INTO BOARD(
    NO,
    TITLE,
    CONTENT,
    CATEGORY_NO,
    WRITER_NO
)VALUES (
    SEQ_BOARD.NEXTVAL,
    ?,
    ?,
    ?,
    ?
)
;

SELECT * FROM BOARD
WHERE DEL_YN ='N'
ORDER BY DESC
;




SELECT * FROM BOARD
            WHERE DEL_YN ='N'
            ORDER BY NO DESC;
            
-- 세미플젝 주요기능 SQL

INSERT INTO MEMBER 
(
    NO,
    ID,
    PWD,
    NICK
) VALUES(
    SEQ_MEMBER.NEXTVAL,
    ?,
    ?,
    ?
);

SELECT * FROM MEMBER
WHERE ID = 'USER01'
AND PWD = '1234'
AND  DEL_YN ='N';


SELECT 
NO,
ID,
PWD,
NICK,
DEL_YN,
ENROLL_DATE,    
MODIFY_DATE
FROM MEMBER
WHERE NO = 2 
AND DEL_YN='N'
;




UPDATE MEMBER 
SET
    MODIFY_DATE = SYSDATE,
    PWD = ?,
    NICK = ?
WHERE NO = ?;
ROLLBACK;


INSERT ALL
INTO BOARD_ATTACHMENT(NO,REF_NO,CHANGE_NAME)VALUES(SEQ_BOARD_ATTACHMENT.NEXTVAL,SEQ_BOARD.CURRVAL,?)
;
SELECT * FROM BOARD_ATTACHMENT;

---첨부파일 시퀀스 값 얻기

CREATE OR REPLACE FUNCTION GET_BOARD_ATTACHMENT_NO
RETURN NUMBER
AS
  N NUMBER;
BEGIN

  SELECT SEQ_BOARD_ATTACHMENT.NEXTVAL
  INTO N
  FROM DUAL;
  
  RETURN N;
END;
/
---------------------------------------------------
--------------------- 함수   -----------------------
---------------------------------------------------

-- 해당함수가 있으면
CREATE OR REPLACE FUNCTION GET_BOARD_ATTACHMENT_NO
RETURN NUMBER
AS
  N NUMBER;
BEGIN

  SELECT SEQ_BOARD_ATTACHMENT.NEXTVAL
  INTO N
  FROM DUAL;
  
  RETURN N;
END;
/
SELECT GET_BOARD_ATTACHMENT_SEQ FROM DUAL;
