-- TABLE
DROP TABLE BOARD CASCADE CONSTRAINTS;

CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(100)   NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
);

-- SEQUENCE
DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD NOCYCLE NOCACHE;

-- INSERT
INSERT INTO BOARD(NO,TITLE,CONTENT) VALUES (SEQ_BOARD.NEXTVAL, ?, ?);

-- UPDATE
UPDATE BOARD
    SET
        TITLE = ?
        , CONTENT = ?
WHERE NO = ?
;

-- DELETE
DELETE BOARD
WHERE NO = ?
;

-- SELECT (목록조회)
SELECT * FROM BOARD
;

-- SELECT (상세조회)
SELECT * FROM BOARD
WHERE NO = ?
;