spring.application.name=app04practice

server.port =8888

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ?????? ?? ?? (Oracle)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##KH
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# MyBatis ??
#mybatis.config-location=classpath:mybatis-config.xml
#mybatis.mapper-locations=classpath:mapper/*.xml
#mybatis.type-aliases-package=com.example.yourpackage.model